"""
Alerts page — live disruption alert feed.
"""

from __future__ import annotations

import streamlit as st
import os
import requests
from src.dashboard.components import severity_badge

API_BASE = os.getenv("API_BASE_URL", "http://localhost:8000")


def render():
    st.header("🚨 Live Disruption Alerts")
    st.caption("Real-time alerts generated by the LangGraph agent pipeline.")

    # Trigger ingest button
    col1, col2 = st.columns([3, 1])
    with col2:
        if st.button("🔄 Run Agent", width="stretch"):
            with st.spinner("Running ingestion + agent pipeline..."):
                try:
                    # Bump timeout to 5 minutes for heavy agent + ingestion work
                    resp = requests.post(f"{API_BASE}/ingest", timeout=300)
                    if resp.ok:
                        data = resp.json()
                        st.success(
                            f"✅ Ingested {data['documents_ingested']} docs, "
                            f"generated {data['alerts_generated']} alerts."
                        )
                    else:
                        st.error(f"API error: {resp.status_code}")
                except requests.Timeout:
                    st.warning("⏱️ Request timed out. The agent is still running in the background. Please refresh in a minute.")
                except requests.ConnectionError:
                    st.error("Cannot connect to API. Is the FastAPI backend running on port 8000?")

    st.divider()

    # Fetch alerts
    try:
        resp = requests.get(f"{API_BASE}/alerts", timeout=10)
        if resp.ok:
            alerts = resp.json()
        else:
            alerts = []
    except requests.ConnectionError:
        st.warning("⚠️ Cannot connect to API backend. Run: `uvicorn src.api.main:app --reload --port 8000`")
        alerts = []

    if not alerts:
        st.info("No alerts yet. Click **Run Agent** to trigger the pipeline.")
        return

    # Display alerts
    for i, alert in enumerate(alerts):
        severity = alert.get("severity", "MEDIUM")
        icon = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(severity, "⚪")

        with st.expander(f"{icon} {alert.get('event', 'Unknown Event')} — {alert.get('shipment_id', 'N/A')}", expanded=(i < 3)):
            col_a, col_b, col_c = st.columns(3)
            col_a.metric("Risk Score", f"{alert.get('risk_score', 0):.2f}")
            col_b.markdown(f"**Severity:** {severity_badge(severity)}", unsafe_allow_html=True)
            col_c.metric("Confidence", f"{alert.get('confidence', 0):.0%}")

            st.markdown(f"**Recommended Action:** {alert.get('recommended_action', 'N/A')}")


if __name__ == "__main__":
    render()
