#!/usr/bin/env python3
"""
Unified Ingestion Pipeline

1. Fetches live news (NewsAPI)
2. Fetches live weather (OpenWeatherMap)
3. Loads historical synthetic disruptions (if available)
4. Upserts everything into ChromaDB for RAG
"""

from __future__ import annotations

import os
import json

from src.ingestion.news_fetcher import NewsFetcher
from src.ingestion.weather_fetcher import WeatherFetcher
from src.rag.vector_store import DisruptionVectorStore

def load_synthetic_history(path: str = "data/synthetic/disruptions.json") -> list[dict]:
    """Load the historical JSON records generated by generate_data.py"""
    if not os.path.exists(path):
        print(f"No historical data found at {path}")
        return []
        
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    # Ensure they have a 'type' tag for the vector store
    for item in data:
        item["type"] = "historical_disruption"
        
    return data

def run_ingestion_pipeline():
    print("Starting ingestion pipeline...")
    
    # 1. Fetch live signals
    news_fetcher = NewsFetcher()
    weather_fetcher = WeatherFetcher()
    
    print("Fetching live news...")
    news_items = news_fetcher.fetch_disruption_news(days_back=2)
    
    print("Fetching live weather alerts...")
    weather_items = weather_fetcher.fetch_weather_alerts()
    
    # 2. Load historical context
    print("Loading historical disruptions...")
    historic_items = load_synthetic_history()
    
    all_documents = news_items + weather_items + historic_items
    
    if not all_documents:
        print("No documents to ingest.")
        return
        
    # 3. Upsert to Vector Store
    print(f"Upserting {len(all_documents)} documents to ChromaDB...")
    vstore = DisruptionVectorStore()
    vstore.upsert_documents(all_documents)
    
    print("✅ Ingestion pipeline complete.")

if __name__ == "__main__":
    run_ingestion_pipeline()
